version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t my-app:latest .
  post_build:
    commands:
      - echo Pushing the Docker image to Docker Hub...
      - docker tag my-app:latest $DOCKERHUB_USERNAME/my-app:latest
      - docker push $DOCKERHUB_USERNAME/my-app:latest

